// frontends/frontend-vue/src/App.vue
<template>
  <div style="padding:20px">
    <h1>FrontEnd Vue — Integrado a BackEnd B</h1>
    <button @click="load">Cargar personas</button>
    <ul>
      <li v-for="p in persons" :key="p.id">{{ p.name }}</li>
    </ul>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { getPersons } from './api';
const persons = ref([]);

async function load(){
  try {
    persons.value = await getPersons();
  } catch(e){
    console.error(e);
    alert('Error al obtener personas');
  }
}
</script>

// frontends/frontend-react/src/App.jsx
import React, { useEffect, useState } from 'react';
import { getItems } from './api';

export default function App(){
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(()=>{
    getItems().then(data=>{ setItems(data); setLoading(false)}).catch(e=>{console.error(e); setLoading(false)});
  },[]);

  return (
    <div style={{padding:20}}>
      <h1>FrontEnd React — Integrado a BackEnd A</h1>
      {loading ? <p>Cargando...</p> : (
        <ul>{items.map(it => <li key={it.id}>{it.name}</li>)}</ul>
      )}
    </div>
  );
}
